language: python
python:
  - "2.7"
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c "create database imager_db;" -U postgres

# command to install dependencies
install:
  - pip install -r requirements.pip
  - pip install coveralls

# command to run tests
script: 
  - cd imagersite
  - python manage.py migrate
  - python manage.py test

after_success:
  - coveralls